// Generates src/openpuck-theme.css from the palette the hand-written panel used
// (docs/index.html:8), so the redesign keeps OpenPuck's colours exactly.
// Skeleton wants a full 50..950 ramp per role; we anchor each ramp on the
// original hex at step 500 and interpolate lightness around it in OKLCH.

const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);

function hexToOklch(hex) {
	const n = parseInt(hex.slice(1), 16);
	const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => srgbToLinear(v / 255));
	const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
	const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
	const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
	const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
	const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
	const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
	const H = (Math.atan2(B, A) * 180) / Math.PI;
	return { L, C: Math.hypot(A, B), H: H < 0 ? H + 360 : H };
}

const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const lerp = (a, b, t) => a + (b - a) * t;
const r2 = (v) => Math.round(v * 100) / 100;

// Chroma falls off towards both ends of the ramp so the tints and shades stay
// believable instead of neon.
const bell = (t) => 0.25 + 0.75 * Math.sin(Math.PI * t) ** 0.7;

function ramp(hex, { lMax = 0.95, lMin = 0.25 } = {}) {
	const { L, C, H } = hexToOklch(hex);
	return STEPS.map((_, i) => {
		const t = i / (STEPS.length - 1);
		const l = t < 0.5 ? lerp(lMax, L, t / 0.5) : lerp(L, lMin, (t - 0.5) / 0.5);
		return { l, c: t === 0.5 ? C : C * bell(t), h: H };
	});
}

function emit(name, stops) {
	const out = [];
	stops.forEach((s, i) => {
		out.push(`\t--color-${name}-${STEPS[i]}: oklch(${r2(s.l)} ${r2(s.c)} ${r2(s.h)});`);
	});
	out.push(`\t--color-${name}-contrast-dark: var(--color-${name}-950);`);
	out.push(`\t--color-${name}-contrast-light: var(--color-${name}-50);`);
	// Pick the readable text colour per step from that step's own lightness
	// rather than a fixed cut-off: OpenPuck's accents are bright, so their 500s
	// need dark text where a typical Skeleton theme's would need light.
	stops.forEach((s, i) => {
		const side = s.l > 0.62 ? 'dark' : 'light';
		out.push(`\t--color-${name}-contrast-${STEPS[i]}: var(--color-${name}-contrast-${side});`);
	});
	return out.join('\n');
}

const PALETTE = {
	primary: '#5b9bd6', // --acc2, the old .primary button / links
	secondary: '#5bd6a0', // --acc, the old .active state and "up" pills
	tertiary: '#8a93a6', // --mut, muted metadata
	success: '#5bd6a0', // --acc
	warning: '#e3b341', // --warn
	error: '#d65b6e', // --bad
};

let css = `/* Generated by tools/gen-theme.mjs -- do not edit by hand. */\n[data-theme='openpuck'] {\n`;
css += `\t--spacing: 0.25rem;\n\t--text-scaling: 1;\n`;
css += `\t--radius-base: 0.5rem;\n\t--radius-container: 0.75rem;\n`;
css += `\t--default-border-width: 1px;\n\t--default-ring-width: 1px;\n`;
css += `\t--corner-shape-base: round;\n\t--corner-shape-container: round;\n`;
css += `\t--color-root-bg-light: var(--color-surface-50);\n`;
// 900, not 950: 950 is reserved for wells recessed below the page (the old
// #0e1017 stat tiles), matching how the original nested its surfaces.
css += `\t--color-root-bg-dark: var(--color-surface-900);\n`;
css += `\t--color-brand-light: var(--color-primary-600);\n`;
css += `\t--color-brand-contrast-light: var(--color-primary-contrast-600);\n`;
css += `\t--color-brand-dark: var(--color-primary-400);\n`;
css += `\t--color-brand-contrast-dark: var(--color-primary-contrast-400);\n`;
for (const [name, hex] of Object.entries(PALETTE)) css += emit(name, ramp(hex)) + '\n';
// Surface is a full neutral scale, not an accent, so it is not anchored at 500.
// These lightness stops are chosen to land on the panel's original greys:
// 950 = #0e1017 stat wells, 900 = #11131a body, 800 = #1b1f2b cards,
// 700 = #272d3d borders, 300 = #8a93a6 muted text, 50 = #e7ecf3 body text.
const SURFACE_L = [0.941, 0.86, 0.76, 0.662, 0.6, 0.5, 0.4, 0.299, 0.241, 0.188, 0.174];
css +=
	emit(
		'surface',
		SURFACE_L.map((l) => ({ l, c: l > 0.9 ? 0.011 : 0.024, h: 270 })),
	) + '\n';
css += '}\n';

const { writeFileSync } = await import('node:fs');
writeFileSync(new URL('../src/openpuck-theme.css', import.meta.url), css);
console.log('wrote src/openpuck-theme.css');
