#pragma once

// Feature report IDs
// See SDL src/joystick/hidapi/steam/controller_constants.h
// enum FeatureReportMessageIDs

#define IBEX_CMD_SET_DIGITAL_MAPPINGS 0x80
#define IBEX_CMD_CLEAR_DIGITAL_MAPPINGS 0x81
#define IBEX_CMD_GET_DIGITAL_MAPPINGS 0x82
#define IBEX_CMD_GET_ATTRIBUTES_VALUES 0x83
#define IBEX_CMD_GET_ATTRIBUTE_LABEL 0x84
#define IBEX_CMD_SET_DEFAULT_DIGITAL_MAPPINGS 0x85
#define IBEX_CMD_FACTORY_RESET 0x86
#define IBEX_CMD_SET_SETTINGS_VALUES 0x87
#define IBEX_CMD_CLEAR_SETTINGS_VALUES 0x88
#define IBEX_CMD_GET_SETTINGS_VALUES 0x89
#define IBEX_CMD_GET_SETTING_LABEL 0x8A
#define IBEX_CMD_GET_SETTINGS_MAXS 0x8B
#define IBEX_CMD_GET_SETTINGS_DEFAULTS 0x8C
#define IBEX_CMD_SET_CONTROLLER_MODE 0x8D
#define IBEX_CMD_LOAD_DEFAULT_SETTINGS 0x8E
#define IBEX_CMD_TRIGGER_HAPTIC_PULSE 0x8F
#define IBEX_CMD_REBOOT_TO_BOOTLOADER 0x90
#define IBEX_CMD_FIRMWARE_UPDATE_REBOOT 0x95
#define IBEX_CMD_TURN_OFF_CONTROLLER 0x9F
#define IBEX_CMD_GET_DEVICE_INFO 0xA1
#define IBEX_CMD_TRITON_A2_OBSERVED_PAIRING_RECORD 0xA2
#define IBEX_CMD_WRITE_CALIBRATION_DATA 0xA2
#define IBEX_CMD_TRITON_A3_BOND_EVENT_OR_STATUS 0xA3
#define IBEX_CMD_CALIBRATE_TRACKPADS 0xA7
#define IBEX_CMD_SET_SERIAL_NUMBER 0xA9
#define IBEX_CMD_GET_TRACKPAD_CALIBRATION 0xAA
#define IBEX_CMD_GET_TRACKPAD_FACTORY_CALIBRATION 0xAB
#define IBEX_CMD_GET_TRACKPAD_RAW_DATA 0xAC
#define IBEX_CMD_ENABLE_PAIRING 0xAD
#define IBEX_CMD_GET_STRING_ATTRIBUTE 0xAE
#define IBEX_CMD_RADIO_ERASE_RECORDS 0xAF
#define IBEX_CMD_RADIO_WRITE_RECORD 0xB0
#define IBEX_CMD_SET_DONGLE_SETTING 0xB1
#define IBEX_CMD_DONGLE_DISCONNECT_DEVICE 0xB2
#define IBEX_CMD_DONGLE_COMMIT_DEVICE 0xB3
#define IBEX_CMD_DONGLE_GET_WIRELESS_STATE 0xB4
#define IBEX_CMD_CALIBRATE_GYRO 0xB5
#define IBEX_CMD_PLAY_AUDIO 0xB6
#define IBEX_CMD_AUDIO_UPDATE_START 0xB7
#define IBEX_CMD_AUDIO_UPDATE_DATA 0xB8
#define IBEX_CMD_AUDIO_UPDATE_COMPLETE 0xB9
#define IBEX_CMD_GET_CHIPID 0xBA
#define IBEX_CMD_GET_BATTERY_DATA 0xBE
#define IBEX_CMD_CALIBRATE_JOYSTICK 0xBF
#define IBEX_CMD_CALIBRATE_ANALOG_TRIGGERS 0xC0
#define IBEX_CMD_SET_AUDIO_MAPPING 0xC1
#define IBEX_CMD_CHECK_GYRO_FW_LOAD 0xC2
#define IBEX_CMD_CALIBRATE_ANALOG 0xC3
#define IBEX_CMD_DONGLE_GET_CONNECTED_SLOTS 0xC4
#define IBEX_CMD_SET_LED_COLOR 0xC5 // ??
#define IBEX_CMD_RESET_IMU 0xCE
#define IBEX_CMD_CALIBRATE_TRACKPAD_STICK 0xD8
#define IBEX_CMD_GET_USER_STORE 0xDB
#define IBEX_CMD_SET_USER_STORE 0xDC
#define IBEX_CMD_SET_TRACKPAD_SIDE 0xE2
#define IBEX_CMD_GET_LED_COLOR 0xE9
#define IBEX_CMD_TRIGGER_HAPTIC_CMD 0xEA // Deck only
#define IBEX_CMD_TRIGGER_RUMBLE_CMD 0xEB // Deck only
#define IBEX_CMD_TRITON_READ_SETTING 0xED
#define IBEX_CMD_TRITON_STAGE_SETTING 0xEE // write
#define IBEX_CMD_TRITON_COMMIT_SETTING 0xEF // save
#define IBEX_CMD_TRITON_DELETE_SETTING 0xF0
#define IBEX_CMD_GET_SYSTEM_INFO 0xF2
#define IBEX_CMD_WRITE_PROVISIONING 0xFE

// Controller setting IDs
// See SDL src/joystick/hidapi/steam/controller_constants.h
// enum ControllerSettings

#define SETTING_LEFT_TRACKPAD_MODE 7
#define SETTING_RIGHT_TRACKPAD_MODE 8
#define SETTING_LIZARD_MODE 9
#define SETTING_SMOOTH_ABSOLUTE_MOUSE 24 // 0x18
#define SETTING_LED_USER_BRIGHTNESS 45 // 0x2d
#define SETTING_ENABLE_RAW_JOYSTICK 46 // 0x2e
#define SETTING_IMU_MODE 48 // 0x30
#define SETTING_WIRELESS_PACKET_VERSION 49 // 0x31
#define SETTING_LEFT_TRACKPAD_CLICK_PRESSURE 52 // 0x34
#define SETTING_RIGHT_TRACKPAD_CLICK_PRESSURE 53 // 0x35
#define SETTING_COUNT 82 // 0x52 - todo: is this really correct?
